### ISSUE TITLE
Run time error: ALPAKA_API_PREFIX(HostUnregister)( ... ) returns 'cudaErrorIllegalAddress'

### ISSUE THREAD

**Issue by steindev** [ComputationalRadiationPhysics/picongpu#3861]
I have a moving window setup that runs on summit on 200+ gpus. Simulations crash systematically at about the same time step with the following error message
```
[cupla] Error: </ccs/home/ksteinig/src/picongpu/include/pmacc/../pmacc/eventSystem/events/kernelEvents.hpp>:170 Crash after kernel launch N5pmacc21KernelInsertParticlesILj256EEE [/ccs/home/ksteinig/src/picongpu/include/pmacc/../pmacc/particles/ParticlesBase.tpp:106 ]
terminate called after throwing an instance of 'std::runtime_error'
  what():  /ccs/home/ksteinig/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp(375) 'ALPAKA_API_PREFIX(HostUnregister)( const_cast<void*>(reinterpret_cast<void const*>(bufImpl.m_pMem)))' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
ERROR:  One or more process (first noticed rank 150) terminated with signal 6 (core dumped)
```
(this run already was compiled with `pic-build -c "-DPMACC_BLOCKING_KERNEL=ON"`)

~~A reduced setup of this simulation that runs only on one node (6 GPUs) finishes without error.~~
EDIT: I Had an error in my density profile resulting in almost no particles in the reduced setup

Probably I did something unusual by setting the supercell size to 4 cells in y direction,
```c++
using SuperCellSize = typename mCT::shrinkTo<mCT::Int<8, 4, 8>, simDim>::type;
```
in `memory.param`. But this shouldn't be a problem, shouldn't it?

I also had to increase the reserved memory to 1GiB already
```c++
constexpr size_t reservedGpuMemorySize = uint64_t(1073741824); // 1 GiB
```
to avoid `out-of-memory` errors.

Any suggestions howto proceed or to fix the error?

**Comment by psychocoderHPC** [comment]
Which version of PIConGPU do you use. In case you use the dev branch please pos the hash.

**Comment by steindev** [comment]
Using latest `dev` does not solve the issue, the error remains
```
[cupla] Error: </ccs/home/ksteinig/src/picongpu/include/pmacc/../pmacc/eventSystem/events/kernelEvents.hpp>:170 Crash after kernel launch N5pmacc21KernelInsertParticlesILj256EEE [/ccs/home/ksteinig/src/picongpu/include/pmacc/../pmacc/particles/ParticlesBase.tpp:106 ]
terminate called after throwing an instance of 'std::runtime_error'
  what():  /ccs/home/ksteinig/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp(375) 'ALPAKA_API_PREFIX(HostUnregister)( const_cast<void*>(reinterpret_cast<void const*>(bufImpl.m_pMem)))' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
[cupla] Error: </ccs/home/ksteinig/src/picongpu/include/pmacc/../pmacc/eventSystem/events/kernelEvents.hpp>:170 Crash after kernel launch N5pmacc21KernelInsertParticlesILj256EEE [/ccs/home/ksteinig/src/picongpu/include/pmacc/../pmacc/particles/ParticlesBase.tpp:106 ]
terminate called after throwing an instance of 'std::runtime_error'
  what():  /ccs/home/ksteinig/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp(375) 'ALPAKA_API_PREFIX(HostUnregister)( const_cast<void*>(reinterpret_cast<void const*>(bufImpl.m_pMem)))' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
```

This is the density about 300 time steps before the simulation crashes
![image](https://user-images.githubusercontent.com/26382442/137142850-9ce4bd83-8302-4d7e-9c58-5b6f9bf18c30.png)

There are in total 12 gpus in y-direction, of course the shown window y-size is comprised of 11 gpus.
And the time of the crash there about 14442800600 particles in the simulation.

This simulation has 8 particles per cell. In order to reduce the probability of memory issues, I let a simulation run with 1 particle per cell.

**Comment by steindev** [comment]
Hmm okay, I had an error in the density profile of my original reduced setup. The original reduced setup ran with almost no particles.

A fixed reduced setup crashes as well. Reducing the number of particles per cell to one makes the simulation run longer, where setting one particle per cell will the simulation run until the target time step. See picture
![image](https://user-images.githubusercontent.com/26382442/137175142-eab80dad-b71f-423c-a121-a675784b902a.png)

Probably there are too many particles piling up in front of the laser leading to an out-of-memory error (as suspected by @psychocoderHPC).

From my side the issue is resolved.

But can we do something to provide a more meaningful error?

**Comment by PrometheusPi** [comment]
@steindev should we close this issue and open a new one regarding the request:
> But can we do something to provide a more meaningful error?

**Comment by steindev** [comment]
Yes would probably be a better way.

**Comment by psychocoderHPC** [comment]
@steindev I found a bug again in alpaka which was already handled in 2019 but was not fixed fully.
https://github.com/alpaka-group/alpaka/pull/1725 is fixing the issue on summit.
@PrometheusPi The same issue should be visible on ZIH taurus-ml.
