### ISSUE TITLE
PIConGPU desktop PC installation fails during execution

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#4004]
PIConGPU experts

I am working on a project that requires PIConGPU to be installed and operate as an application on desktop PCs that may have 1 or more GPUs.  I have not been able to get it working. To facilitate installation I have written a script that installs PIConGPU dependencies that would be run once on the PC, and another script, somewhat similar to the PIConGPU .profile, that sets up system names and temporary directories that are used when PIConGPU is compiled and run.  I have attached these two scripts at the bottom of this post.

Since I am just starting out, I have been attempting to get a PIConGPU simulation running on the CPU.  All of the testing described here has been done with `PIC_BACKEND="omp2b:native"`.  When I run the LaserWakefield simulation, execution begins, runs for about 3 minutes and then exits with an error indication.  I compile the simulation using:

`pic-build 2>err.txt | tee out.txt`

I command execution using:

`tbg -s bash -c etc/picongpu/1.cfg -t etc/picongpu/bash/mpiexec.tpl $SCRATCH/runs/lwfa_001 2>erroutput`

The resulting compile and runtime error files containing the error indications are included in the attachment.

With the help of Klaus Steiniger, I have done a little bit of troubleshooting.  The KelvinHelmholtz simulation runs to completion with no error (that I can tell).  I don’t know if the output produced is complete, but I have saved the ‘scratch’ and ‘picInput’ folders for review if those are needed.  I have run the LaserWakefield simulation with a limited set of TBG plugins (in the 1.cfg file) and then added plugins one at a time, running the simulation after each addition, until execution fails.  Each simulation runs successfully until the simulation with openPMD.  When the openPMD plugin is added, the simulation fails as described above.

I have installed PIConGPU using the dependency and profile scripts on 3 computers, using 2 different Operating Systems, and using a couple of different versions of gcc  Most of the testing has been done on a computer that has a fresh installation of the OS, a driver for the GPU and the dependencies installed by the PIConGPU dependency script, with no other applications.  They all fail in the same way.

My goal right now is to be able to install PIConGPU natively on a desktop PC.  Hopefully, with a bit of help, it wont be hard to get through this first step of running on the CPU, and move on to getting it running with GPU acceleration.  Let me know if you have any ideas for investigating.

Thanks,
Kim

Attachment:
[PIConGPU_on_a_PC_testing.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8164857/PIConGPU_on_a_PC_testing.zip)

**Comment by steindev** [comment]
@kimjohn1 thanks for the detailed description of the issue!
From our previous (offline) communication I know that the setup he runs is the LaserWakefield example with `1.cfg`.
@franzpoeschel do you know of any issues regarding the interaction of the openPMD plugin with mpi for CPU runs? (As this seems to be the cause of the error according to the error message.)

**Comment by franzpoeschel** [comment]
```
[~Series] An error occurred: [Series] Closed iteration has not been written. This is an internal error.
Unhandled exception of type 'St13runtime_error' with message '[Series] Closed iteration has not been written. This is an internal error.', terminating
```

This is the first time that I ever see this error actually happen, will have a look.
I'm not sure how much this error actually can help us solve the issue, since it seems to be a secondary error. (It happens during the ~Series destructor which should not be called until the end of the simulation. The fact that the destructor runs so soon suggests that something else went wrong before.)

The tbg command should create a file `tbg/submit.start` in the output directory. Can you upload that please?

**Comment by franzpoeschel** [comment]
I found out the error: You compiled openPMD-api against HDF5, but PIConGPU uses ADIOS2 as a default backend. Instead of showing a helpful error message, openPMD apparently goes into a dummy backend that does nothing. We should fix that.
In the meantime: You can resolve the error by specifying `--openPMD.ext h5`.

**Comment by franzpoeschel** [comment]
First fix: automatically pick the right extension in PIConGPU https://github.com/ComputationalRadiationPhysics/picongpu/pull/4008/files

**Comment by franzpoeschel** [comment]
Second fix: better error messages in openPMD-api: https://github.com/openPMD/openPMD-api/pull/1214

With this fix, this error turns into:
```
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: opening Series openPMD/stream                                     
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: open file: openPMD/stream.bp                                      
Unhandled exception of type 'N7openPMD5error13WrongAPIUsageE' with message 'Wrong API usage: openPMD-api built
 without support for backend 'ADIOS2'.', terminating                                                          full simulation time:  8sec 703msec = 8.703 sec   
 ```

**Comment by kimjohn1** [comment]
@franzpoeschel 

Thanks for the investigation!
I have changed the 1.cfg file found in `src/picongpu/share/picongpu/examples/LaserWakefield/etc/picongpu` to remove the `--openPMD.ext bp` line and replace it with `--openPMD.ext h5`, and verified that the change is present in the 1.cfg file found in `picInputs/myLWFA/etc/picongpu` after pic-build is executed during the startup sequence.

I still get the early exit during execution and similar error reports during compile and execute.  Error reports are attached along with the `submit.start` file found at `scratch/runs/lwfa_001/tbg` and the 1.cfg file from `picInputs/myLWFA/etc/picongpu`.

Let me know if I should use that `--openPMD.ext h5` expression some other way, or if you can think of what I might do next to isolate and identify whatever it is I have wrong here.

Thanks,
Kim

[PIConGPU error reports.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8181921/PIConGPU.error.reports.tar.gz)

**Comment by sbastrakov** [comment]
Hello @kimjohn1 ,

The option you tried appears correct.

One thing that caught my attention now is that your .cfg file uses both output and checkpointing, both relying on openPMD API but separate. So it might be that the default extension issue as discussed above also applies for checkpoints. In order to check it, please try removing the checkpoint options alltogether (options starting with `--checkpont`). And it that helps, then putting them back and adding `--checkpoint.openPMD.ext h5`.

**Comment by kimjohn1** [comment]
@sbastrakov 

Your instincts serve you well.  The LaserWakefield simulation runs to completion now.  I have attached the 1.cfg file and the picongpu.dependency and picongpu.profile scripts I used to set up and run the simulation.

I am running the simulation on a CPU with 16 hyper-threaded cores.  A total of 2 out of 32 available processing cores are used to process the simulation, which runs for an hour and 45 minutes to finish.  Can you tell me if there is a simple way to task all available cores?  Let me know if that should be opened in a separate post.

Thanks,
Kim 


[dependency and profile scripts 4 March 2022.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8184188/dependency.and.profile.scripts.4.March.2022.tar.gz)
 used to install and run the simulation.

**Comment by sbastrakov** [comment]
Hello @kimjohn1 ,

Glad it helped. For the problem with cores i think it is indeed better to discuss in a separate issue, i just made #4012 for it.

I suggest keeping this one open only till the fix for default extension is merged.

**Comment by steindev** [comment]
Hey @kimjohn1, there is an update with respect to selection of openPMD backends for all backends. PR #4014. This fixes your issue and thus I will close now. If you experience further problems, please open a new issue.
Thanks for reporting!

**Comment by kimjohn1** [comment]
Klaus

    Excellent!  Thanks.

Kim
