### ISSUE TITLE
Energy histogram with PIConGPU 0.6

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#4633]
Hi, I am using the following code to plot the energy histogram for all the electrons of a PIConGPU 0.6 simulation:

```python
from openpmd_viewer import OpenPMDTimeSeries
import matplotlib.pyplot as plt
import numpy as np

ts = OpenPMDTimeSeries("h5/gas_126175.h5", check_all_files=False, backend="h5py")

ux, uy, uz, w = ts.get_particle(
    ["ux", "uy", "uz", "w"], iteration=126175, species="e_all"
)

gamma = np.sqrt(1 + ux**2 + uy**2 + uz**2)
energy = (gamma - 1) * 0.511
print(energy)

Edata = energy
E_hist, nbins = np.histogram(Edata, bins=2048, weights=w)
bincenter = (nbins[:-1] + nbins[1:]) * 0.5

# Create a new figure and a set of subplots
fig, ax = plt.subplots()

# Set the x coordinates of the line plot. Use the midpoint of each bin as x-coordinates.

# Plot the histogram using a line plot
ax.plot(bincenter, E_hist)

# Set the title and labels
ax.set_title("Energy Distribution")
ax.set_xlabel("Energy (MeV)")
ax.set_ylabel("Number of 'real' electrons")

# Display the plot
plt.show()
```

which results in this figure:

![Figure_1](https://github.com/ComputationalRadiationPhysics/picongpu/assets/4405658/18b6ec2f-a314-4c51-bef6-d523651f5254)

I also tried with the `"openpmd-api"` backend, and the results are identical. Furthermore, I tried reading the momentum data directly from the `.h5` file using `openpmd-api` directly, without `openpmd-viewer` - same results.

The energy histogram plugin of PIConGPU gives the following plot:

![e_energyhistogram_all_126000](https://github.com/ComputationalRadiationPhysics/picongpu/assets/4405658/924cec3e-2171-4191-9561-07b5bf7d3c3a)

Notice how the energy scale is vastly different from the one above. 
The thing is that this plotting script works just fine for PIConGPU 0.5, giving sensible values for the energy axis.

Did something change from 0.5 to 0.6 or am I missing something here?

Thanks! 

Here is the `.h5` file in question: [gas_126175.h5](https://transfer.sequanium.de/5sBkUGNPiF/gas_126175.h5) [279 MB].

**Comment by psychocoderHPC** [comment]
@PrometheusPi @steindev could you please have a look into this issue.

**Comment by psychocoderHPC** [comment]
@berceanu Is the last plot created with https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py tool? 
Without any changes? I am wondering because of the axis descriptions, ...

**Comment by psychocoderHPC** [comment]
Could it be that the energy in the openpmd-viewer is wrong because there is a `1e6` on the x-axis.

**Comment by pordyna** [comment]
@berceanu Try adding `ux, uy, uz = ux / w, uy / w, uz / w` before calculating gamma. `openpmd-viewer` should automatically rescale it for you, if `macroWeighted` and `weightingPower` attributes are set correctly, but maybe we have a bug there. Did you rescale when using the API directly (since there, it is not done automatically)?

**Comment by PrometheusPi** [comment]
@berceanu The answer from @pordyna is correct. In PIConGPU, we output the momentum of the macro-particle and it is thus weighting times higher than that of a single electron. 
A quick check revealed that both `macroWeighted = 1` and `weightingPower = 1.0` in PIConGPU. Thus, this is set correctly and most likely these attributes are not checked by the openPMD-viewer.

**Comment by berceanu** [comment]
But then how come the same code works fine with output from PIConGPU 0.5?

**Comment by PrometheusPi** [comment]
Very good question @berceanu. Since this is a quite old part of the openPMD standard, we might have a bug in how we set the attribute with the newer openPMD-api implementation. Thanks for pointing this out. I will check what is going on.

**Comment by PrometheusPi** [comment]
I did not see any changes in where the attributes are placed and how they are named in picongpu 0.4.2 (hdf5) and picongpu current dev (0.7.0-dev) (adios2).
Both `macroWeighted` and `weightingPower` are located on the group level of `momentum`. 

@berceanu Cold you please run the following code on one of your openPMD output files for both the case where it works and where it doesn't:
HDF5:
```bash
h5ls -vr __your_file__.h5  | grep "momentum Group" -A 10
```

ADIOS:
```bash
bpls -a __your_file__.bp | grep momentum
```

and post the result here.

**Comment by PrometheusPi** [comment]
One possible problem might be the extension specification: https://github.com/openPMD/openPMD-viewer/blob/c195c4244a4ef0322e1abe05bac63b35f90f562f/openpmd_viewer/openpmd_timeseries/data_reader/io_reader/particle_reader.py#L78 
I will check whether we changed something ...

**Comment by PrometheusPi** [comment]
@franzpoeschel our `/openPMDextension` contains `0`. I am not sure how this is handled by openPMD-viewer, but might this be a problem since we perhaps just skip the if-case linked above?

**Comment by berceanu** [comment]
> I did not see any changes in where the attributes are placed and how they are named in picongpu 0.4.2 (hdf5) and picongpu current dev (0.7.0-dev) (adios2). Both `macroWeighted` and `weightingPower` are located on the group level of `momentum`.
> 
> @berceanu Cold you please run the following code on one of your openPMD output files for both the case where it works and where it doesn't: HDF5:
> 
> ```shell
> h5ls -vr __your_file__.h5  | grep "momentum Group" -A 10
> ```
> 
> ADIOS:
> 
> ```shell
> bpls -a __your_file__.bp | grep momentum
> ```
> 
> and post the result here.

They look identical 

```console
$ h5ls -vr picongpu05.h5  | grep "momentum Group" -A 10
/data/126175/particles/e_highGamma/momentum Group
    Attribute: macroWeighted scalar
        Type:      native unsigned int
    Attribute: timeOffset scalar
        Type:      native float
    Attribute: unitDimension {7}
        Type:      native double
    Attribute: weightingPower scalar
        Type:      native double
    Location:  1:50349552
    Links:     1
$ h5ls -vr picongpu06.h5  | grep "momentum Group" -A 10
/data/126175/particles/e_all/momentum Group
    Attribute: macroWeighted scalar
        Type:      native unsigned int
    Attribute: timeOffset scalar
        Type:      native float
    Attribute: unitDimension {7}
        Type:      native double
    Attribute: weightingPower scalar
        Type:      native double
    Location:  1:62929824
    Links:     1
```

**Comment by PrometheusPi** [comment]
Thanks @berceanu 
I assume you used `libSplash` in 0.5 and `openPMD-api` in 0.6 as your hdf5 library, right?

**Comment by berceanu** [comment]
> @franzpoeschel our `/openPMDextension` contains `0`. I am not sure how this is handled by openPMD-viewer, but might this be a problem since we perhaps just skip the if-case linked above?

For the PIConGPU 5.0 file:

```
   ATTRIBUTE "openPMDextension" {
      DATATYPE  H5T_STD_U32LE
      DATASPACE  SCALAR
      DATA {
      (0): 1
      }
   ```
   
   and for the 6.0 file:
   
   ```
      ATTRIBUTE "openPMDextension" {
      DATATYPE  H5T_STD_U32LE
      DATASPACE  SCALAR
      DATA {
      (0): 0
      }
   ```

**Comment by PrometheusPi** [comment]
At least there, we have a difference.

**Comment by berceanu** [comment]
It seems that `openpmd-viewer` reads particle data using either [this code](https://github.com/openPMD/openPMD-viewer/blob/dda94285fc20df404d5822dcc13ada464f2aafa5/openpmd_viewer/openpmd_timeseries/data_reader/io_reader/particle_reader.py#L78) or [this code](https://github.com/openPMD/openPMD-viewer/blob/dda94285fc20df404d5822dcc13ada464f2aafa5/openpmd_viewer/openpmd_timeseries/data_reader/h5py_reader/particle_reader.py#L71), depending on the backend. However, both functions have the same `if` statement where they check the extension:

```python
    # For ED-PIC: if the data is weighted for a full macroparticle,
    # divide by the weight with the proper power
    # (Skip this if the current record component is the weight itself)
    if 'ED-PIC' in extensions and ompd_record_name != 'weighting':
        macro_weighted = record.get_attribute('macroWeighted')
        weighting_power = record.get_attribute('weightingPower')
        ...
```
  
Sorry @PrometheusPi just saw this is the same code you linked to above, basically.

**Comment by steindev** [comment]
I am not sure it worked previously (altough I was under the same impression until @psychocoderHPC and @PrometheusPi corrected me). I have a jupyter notebook for data analysis from 2020, where I already had to divide the momentum component by the weighting in order to obtain $\gamma \beta_i$.
I might have confused the particle momentum data in the openPMD plugin with the phase space plugin, where the momentum component written indeed is $\gamma \beta_i$.

Anyway. I guess your issue is resolved @berceanu?

**Comment by PrometheusPi** [comment]
@steindev I would say that this issue is not solved. The required attributes are the same in both versions, but somehow we seem to set something wrongly with openPMD-api thus that openPMD-viewer does not recognize that we have a weighted quantity.

**Comment by franzpoeschel** [comment]
I'm currently on vacation, so I can't have a more detailed look. But the easiest way to confirm the suspicion above would probably be to quickly edit those if lines in your local installation of the openpmd-viewer and see if this changes the behavior. If so, the fix should be relatively simple at least.

There was recently a similar issue with ignored scaling in PIConGPU data, but this does not look like that? https://github.com/openPMD/openPMD-viewer/pull/363

**Comment by berceanu** [comment]
OK, so I dug a bit deeper in the `openpmd-viewer` codebase and the standard. The relevant code seems to be [here](https://github.com/openPMD/openPMD-viewer/blob/dda94285fc20df404d5822dcc13ada464f2aafa5/openpmd_viewer/openpmd_timeseries/data_reader/io_reader/params_reader.py#L55) for the `openpmd-api` backend and [here](https://github.com/openPMD/openPMD-viewer/blob/dda94285fc20df404d5822dcc13ada464f2aafa5/openpmd_viewer/openpmd_timeseries/data_reader/h5py_reader/params_reader.py#L61) for the older `h5py` backend:

```python
    # Find out supported openPMD extensions claimed by this file
    # note: a file might implement multiple extensions
    known_extensions = {'ED-PIC': np.uint32(1)}
    bitmask_all_extensions = series.openPMD_extension
    params['extensions'] = []
    for extension, bitmask in known_extensions.items():
        # This uses a bitmask to identify activated extensions
        # efficiently in static programming languages via
        # a single attribute and a binary AND (&) operation.
        # Standard: https://git.io/vwnMw
        # Bitmasks: https://en.wikipedia.org/wiki/Mask_%28computing%29
        if bitmask_all_extensions & bitmask == bitmask:
            params['extensions'].append(extension)
```

Based on the values of `ATTRIBUTE "openPMDextension"` from the two `HDF5` files above, the bitwise AND operation will produce an empty list `params['extensions']=[]` in the case of PIConGPU 0.6 and `params['extensions'] = ['ED-PIC']` in the case of PIConGPU 0.5. Therefore the `if 'ED-PIC' in extensions` test above would only yield `True` for PIConGPU 0.5, and result in auto-scaling by the weights. 

Further details about `openPMDextension` can be found in the [standard](https://git.io/vwnMw).

**Comment by PrometheusPi** [comment]
Thanks a lot @berceanu. Then we need to fix setting `openPMDextension` in PIConGPU correctly.

**Comment by psychocoderHPC** [comment]
@berceanu could you please check PR #4636 this should solve your issue.

**Comment by steindev** [comment]
@berceanu please do not forget to close the issue if it is resolved.
